#!/bin/bash

log_script_start() {
  local script_name="${BASH_SOURCE[1]}"
  echo
  echo "================================================================================"
  echo "  STARTING SCRIPT: $script_name"
  echo "================================================================================"
  echo
}

log_script_end() {
  local script_name="${BASH_SOURCE[1]}"
  echo
  echo "================================================================================"
  echo "  ENDING SCRIPT: $script_name"
  echo "================================================================================"
  echo
}
