#!/bin/bash
# Runs bash in Docker, forwarding args

xhost +local:docker # allow X11 for Docker

docker run -it --rm \
  --name xilinx-vitis \
  -e DISPLAY=$DISPLAY \
  -v /tmp/.X11-unix:/tmp/.X11-unix \
  -v /opt/Xilinx/:/opt/Xilinx \
  -v ~/workspace:/home/developer/workspace \
  --device /dev/bus/usb:/dev/bus/usb \
  xilinx_docker \
  bash
